<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\AioAmazonSalesChannel\Block\Adminhtml\Index $block */ ?>
<?php if ($block->getIframeUrl()) : ?>
<iframe width="<?= $block->getIframeWidth() ?>"
        height=<?= $block->getIframeHeight() ?>"
        src="<?= $block->getIframeUrl() ?>"
<?php else: ?>
No URL provided
<?php endif; ?>
